dj_lab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('django_lab.urls', 'django_lab'), namespace='django_lab'))
]

django_lab/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import AnimeCreateView, AnimeDeleteView, AnimeEditView, LoginView, RegistrationView

urlpatterns = [
    path('', AnimeCreateView.as_view(), name='an-edit'),
    path('<int:pk>/', AnimeEditView.as_view(), name='an-view'),
    path('<int:pk>/delete', AnimeDeleteView.as_view(), name='an-delete'),

    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(next_page='/'), name='logout'),
    path('register', RegistrationView.as_view(), name='registration'),
]

django_lab/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from redis import Redis

redis = Redis(settings.REDIS_HOST, port=int(settings.REDIS_PORT))


class AnimeWatching(models.Model):
    WATCHING = [
        ('Finished', 'Finished'),
        ('In process', 'In process'),
        ('Dropped', 'Dropped'),
        ('Plans to watch', 'Plans to watch'),
    ]

    RATING = [
        ('11/10', '11/10'),
        ('10/10', '10/10'),
        ('9/10', '9/10'),
        ('8/10', '8/10'),
        ('7/10', '7/10'),
        ('6/10', '6/10'),
        ('5/10', '5/10'),
        ('4/10', '4/10'),
        ('3/10', '3/10'),
        ('2/10', '2/10'),
        ('1/10', '1/10'),
        ('0/10', '0/10'),
        ('--/10', '--/10'),
    ]

    anime_name = models.CharField(max_length=100)
    rating = models.CharField(max_length=5, choices=RATING)
    watching = models.CharField(max_length=50, choices=WATCHING)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def as_dict(self):
        return {
            'anime_name': self.anime_name,
            'rating': self.rating,
            'watching': self.watching,
        }

    @classmethod
    def from_dict(cls, data):
        return cls(**data)

django_lab/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import AnimeWatching


class AnimeForm(forms.ModelForm):
    class Meta:
        model = AnimeWatching
        fields = '__all__'


class RegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput())

    def form_valid(self):
        pass

    class Meta:
        model = User
        fields = ['username', 'password', 'password1', 'first_name', 'last_name', 'email']
        widgets = {
            'email': forms.EmailInput(),
            'password': forms.PasswordInput(),
        }

django_lab/views.py
import json

from django.http import HttpResponseRedirect
from django.conf import settings
from django.contrib.auth.views import LoginView as OldLoginView
from django.shortcuts import render
from django.views import View
from django.views.generic import CreateView
from redis import Redis

from .models import AnimeWatching
from .forms import AnimeForm, RegistrationForm

redis = Redis(settings.REDIS_HOST, port=int(settings.REDIS_PORT))


class AnimeCreateView(View):
    def get(self, request):
        if request.user.is_anonymous:
            anime = []
        else:
            anime = AnimeWatching.objects.filter(user=request.user)
        form = AnimeForm()

        return render(request, 'create_instance.html', {
            'form': form.as_p(),
            'anime': anime,
        })

    def post(self, request):
        form = AnimeForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')


class AnimeEditView(View):
    def get(self, request, pk):
        cached_anime = redis.get(pk)
        if cached_anime is not None:
            anime = AnimeWatching.from_dict(json.loads(cached_anime))
        else:
            anime = AnimeWatching.objects.get(pk=pk)
            redis.set(pk, json.dumps(anime.as_dict()))

        form = AnimeForm(instance=anime)

        return render(request, 'edit_instance.html', {
            'form': form.as_p(),
        })

    def post(self, request, pk):
        anime = AnimeWatching.objects.get(pk=pk)
        form = AnimeForm(request.POST, instance=anime)

        if form.is_valid():
            form.save()
            redis.delete(pk)
            return HttpResponseRedirect('/')


class AnimeDeleteView(View):
    def post(self, request, pk):
        anime = AnimeWatching.objects.get(pk=pk)
        anime.delete()
        redis.delete(pk)
        return HttpResponseRedirect('/')


class LoginView(OldLoginView):
    redirect_authenticated_user = True
    template_name = 'login.html'


class RegistrationView(CreateView):
    form_class = RegistrationForm
    template_name = 'registration.html'

    def get_success_url(self):
        return self.kwargs.get('next', '/')

    def form_valid(self, form):
        redirect = super().form_valid(form)
        self.object.set_password(form.cleaned_data['password'])
        self.object.save()
        return redirect

templates/create_instance.html
{% extends 'layouts/base.html' %}

{% block content %}
    {% include 'navigation.html' %}

    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>

    <table border="1" cellspacing="0" cellpadding="5">
        <thead>
            <td>ID</td>
            <td>Anime Name</td>
            <td>Rating</td>
            <td>Watching</td>
            <td>Additional actions</td>
        </thead>
        {% for an in anime %}
        <tr>
            <td><a href="/{{ an.id }}/">{{ an.id }}</a></td>
            <td>{{ an.anime_name }}</td>
            <td>{{ an.rating }}</td>
            <td>{{ an.watching }}</td>
            <td>
                <form method="post" action="/{{ an.id }}/delete">
                    {% csrf_token %}
                    <input type="submit" value="Delete">
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/edit_instance.html
{% extends 'layouts/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Edit">
    </form>
    <form method="post" action="delete">
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>
{% endblock %}

templates/layouts/base.html
<html>
<head>
    <link rel="icon" href="https://www.meme-arsenal.com/memes/1a954f4f91f34b54486a37004e5fc25a.jpg">
    <title>Anime List</title>
{% block head %}{% endblock %}
</head>

<body>
{% block content %}{% endblock %}
</body>

</html>

templates/login.html
{% extends 'layouts/base.html' %}

{% block content %}
    {% include 'navigation.html' %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Log in">
    </form>
{% endblock %}

templates/navigation.html
<nav>
    <ul>
        {% if user.is_authenticated %}
            <li>You are logged in as {{ user.username }}</li>
            <li><a href="{% url 'django_lab:logout' %}?next=/{{ path }}">Log out</a></li>
        {% else %}
            <li><a href="{% url 'django_lab:login' %}?next=/{{ path }}">Log in</a></li>
        {% endif %}
        <li><a href="{% url 'django_lab:registration' %}?next=/{{ path }}">Register</a></li>
    </ul>
</nav>

templates/registration.html
{% extends 'layouts/base.html' %}

{% block content %}
    {% include 'navigation.html' %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}